import { useState } from 'react';
import { Alert, Button, Card, Col, Input, Row, Space, Tag, Typography } from 'antd';
import { api, fmtPct } from '../api';
import { useModelReady } from '../hooks';
import FeatureTable from '../components/FeatureTable';
import ReasonCodes from '../components/ReasonCodes';

const { Title, Paragraph, Text } = Typography;

/* Samples mix model-written and human-written reviews so the contrast is
   visible immediately. The first two are what LLM output typically looks
   like; the last two are real Yelp reviews. */
const SAMPLES = [
  {
    label: 'Machine-like, polished',
    text:
      'This restaurant offers a delightful culinary experience that truly satisfies the palate. ' +
      'The ambiance is warm and inviting, making it an ideal choice for both casual dining and special ' +
      'occasions. The service was attentive and the flavors were perfectly balanced.',
  },
  {
    label: 'Machine-like, mixed opinion',
    text:
      'My visit to this establishment was a mixed experience overall. The appetizers were quite good, ' +
      'but the main course was somewhat disappointing. The service was adequate and the prices were ' +
      'reasonable for the area. I would consider returning to try other options.',
  },
  {
    label: 'Human-written',
    text:
      'I came here on a Tuesday with my girlfriend. We waited about 25 minutes for a table which was ' +
      'annoying but the ramen was worth it. Broth was rich and the chashu melted. $16 a bowl is steep ' +
      'though. Parking is a nightmare. Would come back.',
  },
  {
    label: 'Human-written, angry',
    text:
      'DO NOT EAT HERE. Waited 45 min for cold fries and a soggy burger. The guy at the counter ' +
      'argued with me when I asked for a refund. $18 wasted. Never again.',
  },
];

export default function Analyzer() {
  const health = useModelReady();
  const [text, setText] = useState('');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState(null);

  async function analyze() {
    if (!text.trim()) return;
    setLoading(true);
    setError(null);
    try {
      const r = await api('/api/analyze', {
        method: 'POST',
        body: JSON.stringify({ text }),
      });
      setResult(r);
    } catch (e) {
      setError(e.message);
    } finally {
      setLoading(false);
    }
  }

  const isMachine = result?.prediction === 'MACHINE';

  return (
    <div>
      <Title level={2} style={{ marginTop: 4 }}>
        Frede - Fake (Machine-Generated) Review Detector
      </Title>
      <Paragraph type="secondary">
        Paste a review to see whether it was <strong>written by a person</strong> or{' '}
        <strong>generated by a language model</strong>, and which signals drove the call.
      </Paragraph>

      {!health.ready && health.error && (
        <Alert
          type="error"
          showIcon
          message={`Detector not ready: ${health.error} — run make stage2 first.`}
          style={{ marginBottom: 16 }}
        />
      )}

      <Card style={{ marginBottom: 16 }}>
        <Text strong>Enter a review</Text>
        <Input.TextArea
          rows={6}
          value={text}
          onChange={(e) => setText(e.target.value)}
          placeholder="Type or paste a review here..."
          style={{ marginTop: 8 }}
        />
        <Row gutter={8} style={{ marginTop: 12 }}>
          <Col>
            <Button type="primary" loading={loading} disabled={!health.ready} onClick={analyze}>
              Analyze
            </Button>
          </Col>
          <Col>
            <Button
              onClick={() => {
                setText('');
                setResult(null);
                setError(null);
              }}
            >
              Clear
            </Button>
          </Col>
        </Row>
        <Space wrap size={[8, 8]} style={{ marginTop: 14 }}>
          <Text type="secondary">Try a sample:</Text>
          {SAMPLES.map((s, i) => (
            <Button key={i} size="small" onClick={() => setText(s.text)}>
              {s.label}
            </Button>
          ))}
        </Space>
      </Card>

      {error && <Alert type="error" showIcon message={error} style={{ marginBottom: 16 }} />}

      {result && (
        <>
          <Card style={{ marginBottom: 16 }}>
            <Tag
              color={isMachine ? 'red' : 'green'}
              style={{ fontSize: 24, fontWeight: 700, padding: '4px 16px', borderRadius: 8 }}
            >
              {result.prediction}
            </Tag>
            <div style={{ marginTop: 8 }}>
              <Text type="secondary">
                P(machine-written): <Text strong>{fmtPct(result.machine_prob)}</Text> · Confidence:{' '}
                <Text strong>{fmtPct(result.confidence)}</Text> · analyzed in{' '}
                <Text strong>{result.elapsed_ms} ms</Text>
              </Text>
            </div>
            <div style={{ marginTop: 8 }}>
              <Text type="secondary" style={{ fontSize: 12 }}>
                Flagged as machine at the {fmtPct(result.threshold)} threshold — the cut calibrated
                to keep false positives on real reviews at 1%.
              </Text>
            </div>
          </Card>

          <Alert
            type="info"
            showIcon
            message="Scope of this model"
            description={result.scope_note}
            style={{ marginBottom: 16 }}
          />

          <Row gutter={[16, 16]}>
            <Col xs={24} lg={12}>
              <Card title="Token predictability">
                <div
                  className="highlighted-html"
                  dangerouslySetInnerHTML={{ __html: result.highlighted_html }}
                />
              </Card>
            </Col>
            <Col xs={24} lg={12}>
              <Card title="Reason codes">
                <ReasonCodes items={result.reason_codes} />
              </Card>
            </Col>
          </Row>

          <Card title="Feature contributions" style={{ marginTop: 16 }}>
            <FeatureTable items={result.features} />
          </Card>

          <Card title="Summary" style={{ marginTop: 16 }}>
            <Paragraph style={{ marginBottom: 0 }}>{result.summary}</Paragraph>
          </Card>
        </>
      )}
    </div>
  );
}
